/* Generate src/team/bundle.ts from the ICOR for Life Scaffold.
 *
 * The one-click setup writes an AI team into a vault that has none. The
 * contracts and bios it writes are the SCAFFOLD's own files, read from the
 * scaffold repository at generation time and embedded verbatim, so the plugin
 * never carries a second, drifting copy of an agent's contract. The scaffold
 * is the source of truth; this file is a copier.
 *
 * It fails loudly. A missing agent file is not a warning and not a skip: a
 * bundle with seven agents where eight were promised is a setup that lies.
 *   ICOR_SCAFFOLD_DIR   the scaffold checkout (default below)
 *   ICOR_AVATARS_DIR    256px avatars, <slug>.png (default below)
 *   ICOR_TEAM_ONLY      comma-separated slugs, for a partial build while the
 *                       scaffold is still being extended. Stated in the
 *                       generated header so a partial bundle cannot pass as
 *                       a full one. */
import { readFileSync, existsSync, writeFileSync } from 'node:fs';
import { resolve, join } from 'node:path';
import process from 'node:process';

const SCAFFOLD = process.env.ICOR_SCAFFOLD_DIR ?? '/Users/tom/projects/icor-for-life-scaffold';
const AVATARS = process.env.ICOR_AVATARS_DIR
  ?? '/private/tmp/claude-501/-Users-tom-My-Life-Folder---TR/bbd7d13c-ef05-494f-883d-d6b9898a7a1b/scratchpad/avatars-256';
const AGENTS_DIR = join(SCAFFOLD, '06 AI Team', 'Agents');

export const TEAM = ['Larry', 'Penn', 'Pax', 'Nolan', 'Mack', 'Silas', 'Iris', 'Charta'];

const only = (process.env.ICOR_TEAM_ONLY ?? '').split(',').map((s) => s.trim().toLowerCase()).filter(Boolean);
const wanted = only.length ? TEAM.filter((n) => only.includes(n.toLowerCase())) : TEAM;

const missing = [];
function must(path) {
  if (!existsSync(path)) {
    missing.push(path);
    return '';
  }
  return path;
}

const agents = wanted.map((name) => {
  const slug = name.toLowerCase();
  const agentPath = must(join(AGENTS_DIR, name, 'AGENT.md'));
  const bioPath = must(join(AGENTS_DIR, name, `${name}.md`));
  const avatarPath = must(join(AVATARS, `${slug}.png`));
  return { name, slug, agentPath, bioPath, avatarPath };
});
const indexPath = must(join(AGENTS_DIR, 'agent-index.md'));

if (missing.length) {
  console.error('embed-team: refusing to write a bundle with files missing:');
  for (const m of missing) console.error(`  ${m}`);
  process.exit(1);
}

const rows = agents.map((a) => ({
  name: a.name,
  slug: a.slug,
  agent: readFileSync(a.agentPath, 'utf8'),
  bio: readFileSync(a.bioPath, 'utf8'),
  avatarBase64: readFileSync(a.avatarPath).toString('base64'),
}));

const partial = wanted.length !== TEAM.length;
const header = [
  '/* GENERATED by tools/embed-team.mjs. Do not edit by hand.',
  ` * Source: the ICOR for Life Scaffold at generation time (${new Date().toISOString().slice(0, 10)}).`,
  ` * Agents: ${wanted.join(', ')}.`,
  partial ? ` * PARTIAL BUNDLE: ${TEAM.length - wanted.length} of the ${TEAM.length} agents are absent. Re-run without ICOR_TEAM_ONLY before release.` : ` * Complete: all ${TEAM.length} agents present.`,
  ' * Regenerate with `npm run embed:team`. */',
  '',
  'export interface BundledAgent {',
  '  name: string;',
  '  slug: string;',
  '  /** AGENT.md, verbatim from the scaffold. */',
  '  agent: string;',
  '  /** <Name>.md, the user-facing bio, verbatim. */',
  '  bio: string;',
  '  /** A 256px PNG. */',
  '  avatarBase64: string;',
  '}',
  '',
  'export interface TeamBundle {',
  '  /** True when every agent of the scaffold team is in the bundle. */',
  '  complete: boolean;',
  '  agents: BundledAgent[];',
  '  agentIndex: string;',
  '}',
  '',
].join('\n');

const body = `export const TEAM_BUNDLE: TeamBundle = ${JSON.stringify({ complete: !partial, agents: rows, agentIndex: readFileSync(indexPath, 'utf8') }, null, 2)};\n`;

const out = resolve('src/team/bundle.ts');
writeFileSync(out, header + body);
console.log(`embed-team: wrote ${out} with ${rows.length} agent(s)${partial ? ' (PARTIAL)' : ''}`);
